{% set name = "version-parser" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/version_parser-{{ version }}.tar.gz
  sha256: 7320b00cab8a04694206818c9129864dd0783cec0c0eff25b1c922e7d838dbc0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - version_parser
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/eieste/VersionParser
  summary: This package can parse and compare semantic versioning.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tylere
